services:
    oro_google_integration.oauth_user_provider:
        class: Oro\Bundle\GoogleIntegrationBundle\OAuth\GoogleOAuthUserProvider
        arguments:
            - '@oro_user.manager'
            - '@oro_config.global'
        tags:
            - { name: oro.sso.oauth_user_provider, resource_owner: google }

    oro_google_integration.event_listener.user_email_change:
        class: Oro\Bundle\GoogleIntegrationBundle\EventListener\UserEmailChangeListener
        tags:
            - { name: doctrine.orm.entity_listener, entity: Oro\Bundle\UserBundle\Entity\User, event: preUpdate }
