doctrine:
    orm:
        entity_managers:
            config:
                mappings:
                    OroConfigBundle:
                        mapping:   true
                        is_bundle: true
                metadata_cache_driver:
                    type: service
                    id:   oro_config.cache.doctrine_metadata
