api:
    entities:
        Oro\Bundle\AttachmentBundle\Entity\Attachment:
            documentation_resource: '@OroAttachmentBundle/Resources/doc/api/attachment.md'
            fields:
                target:
                    data_type:    association:manyToOne
                    description:  A record to which the attachment record belongs to.
            actions:
                            create:
                                fields:
                                    target:
                                        form_options:
                                            constraints:
                                                - NotNull: ~
 #           subresources:
 #               target:
 #                   actions:
 #                      get_subresource:
 #                          documentation: Get full information about a record to which the attachment belongs to.
 #                       get_relationship:
 #                           documentation: Get a record to which the attachment belongs to.
 #                       update_relationship:
 #                           documentation: Update a record to which the attachment belongs to.
        Oro\Bundle\AttachmentBundle\Entity\File:
            documentation_resource: '@OroAttachmentBundle/Resources/doc/api/file.md'
            fields:
                filename:
                    exclude: true
                extension:
                    exclude: true
                content:
                    description: The content of the file as a string.
                    data_type: string
                    property_path: file
                    depends_on: [filename]
