knp_gaufrette:
    filesystems:
        attachments:
            adapter:    private
            alias:      attachments_filesystem
        mediacache:
            adapter:    public
            alias:      mediacache_filesystem
        protected_mediacache:
            adapter:    private
            alias:      protected_mediacache_filesystem

    stream_wrapper: ~
