dist: xenial

language: php

git:
    depth: 2
    
addons:
    apt_packages:
        - parallel

branches:
  only:
    - master
    - /^\d+\.\d+$/

php:
    - 7.1

env:
  - COMPOSER=travis.json

cache:
  directories:
    - $HOME/.composer

before_install:
  - |
    nanoseconds () {
      local cmd="date"
      local format="+%s%N"
      local os=$(uname)
      if hash gdate > /dev/null 2>&1; then
        cmd="gdate"
      elif [[ "$os" = Darwin ]]; then
        format="+%s000000000"
      fi
      $cmd -u $format
    }
    export -f nanoseconds
      # tfold is a helper to create folded reports
      tfold () {
          local title="🐘 $PHP $1"
          local fold=$(echo $title | sed -r 's/[^-_A-Za-z0-9]+/./g')
          shift
          local id=$(printf %08x $(( RANDOM * RANDOM )))
          local start=$(nanoseconds)
          echo -e "travis_fold:start:$fold"
          echo -e "travis_time:start:$id"
          echo -e "\\e[1;34m$title\\e[0m"
          bash -xc "$*" 2>&1
          local ok=$?
          local end=$(nanoseconds)
          echo -e "\\ntravis_time:end:$id:start=$start,finish=$end,duration=$(($end-$start))"
          (exit $ok) &&
              echo -e "\\e[32mOK\\e[0m $title\\n\\ntravis_fold:end:$fold" ||
              echo -e "\\e[41mKO\\e[0m $title\\n"
          (exit $ok)
      }
      export -f tfold

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer global require symfony/flex --no-scripts
  - cp dev.json travis.json # avoid dev.lock file and composer.json with a stable version
  - composer install --prefer-dist --optimize-autoloader --no-interaction  --no-suggest --profile
  - set +e; DIFF=$(git diff --name-only --diff-filter=ACMR $TRAVIS_COMMIT_RANGE | grep -e ".*\.php$"); set -e;

script:
  - ls -d src/*/*/* | parallel --gnu "tfold {} ./vendor/bin/phpunit --testsuite=unit {}"
  - ls -d src/*/*/* | parallel --gnu "tfold {} ./vendor/bin/phpcs {} -p --encoding=utf-8 --extensions=php --standard=PSR2"
  - ls -d src/*/*/* | parallel --gnu "tfold {} ./vendor/bin/php-cs-fixer fix --dry-run --config=./build/.php_cs --path-mode=intersection {}"
  - if [[ $DIFF ]]; then ./vendor/bin/phpmd ${DIFF//$'\n'/,} text ./build/phpmd.xml --suffixes php; fi
