sudo: false

language: php

php:
    - 5.6
    - 7.0

cache:
  directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer global show fxp/composer-asset-plugin 1.2.2 || composer global require fxp/composer-asset-plugin:1.2.2
  - travis_wait composer install --prefer-dist --optimize-autoloader --no-interaction
  - DIFF=$(git diff --name-only --diff-filter=ACMR $TRAVIS_COMMIT_RANGE)

script:
  - phpunit
  - ./vendor/bin/phpcs ${DIFF} -p --encoding=utf-8 --extensions=php --standard=psr2
  - ./vendor/bin/phpmd ${DIFF//$'\n'/,} text codesize --suffixes php
