sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

env:
  - SYMFONY_VERSION=2.7.*

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  # PHP config
  - if ! [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then phpenv config-rm xdebug.ini ; fi
  - if ! [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then phpenv config-add travis.php.ini ; fi
  # HHVM config
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then cp travis.hhvm.php.ini /etc/hhvm/php.ini  ; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then sudo service hhvm restart ; sleep 1 ; fi
  # Composer
  - composer self-update
  - travis_wait composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist --update-no-dev
  - travis_wait composer require squizlabs/php_codesniffer:~2 --prefer-dist --update-no-dev

script:
  - phpunit
  - ./vendor/bin/phpcs ./src -p --encoding=utf-8 --extensions=php --standard=psr2
