operations:
    DELETE:
        exclude_entities:
            - Oro\Bundle\LocaleBundle\Entity\Localization
        exclude_datagrids:
            - oro-locale-localizations-grid

    oro_locale_localization_delete:
        extends: DELETE
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - entities
            - datagrids
            - exclude_datagrids
            - exclude_entities
        entities:
            - Oro\Bundle\LocaleBundle\Entity\Localization
        datagrids:
            - oro-locale-localizations-grid
        frontend_options:
            confirmation:
                message: oro.locale.localization.delete_confirm
                component: oroui/js/delete-confirmation
        actions:
            - '@assign_url':
                attribute: $.rebuildCacheUrl
                route: oro_translation_translation_index
            - '@trans':
                attribute: $.rebuildCacheMessage
                id: oro.translation.translation.rebuild_cache_required
                params:
                    '%%path%%': $.rebuildCacheUrl
            - '@flash_message':
                message: $.rebuildCacheMessage
                type: 'warning'
