parameters:
    oro_form.type.date.class:                                    Oro\Bundle\FormBundle\Form\Type\OroDateType
    oro_form.type.datetime.class:                                Oro\Bundle\FormBundle\Form\Type\OroDateTimeType
    oro_form.type.time_interval.class:                           Oro\Bundle\FormBundle\Form\Type\OroTimeIntervalType
    oro_form.type.money.class:                                   Oro\Bundle\FormBundle\Form\Type\OroMoneyType
    oro_form.type.percent.class:                                 Oro\Bundle\FormBundle\Form\Type\OroPercentType
    oro_form.type.entity_identifier.class:                       Oro\Bundle\FormBundle\Form\Type\EntityIdentifierType
    oro_form.type.jqueryselect2_hidden.class:                    Oro\Bundle\FormBundle\Form\Type\OroJquerySelect2HiddenType
    oro_form.type.icon.class:                                    Oro\Bundle\FormBundle\Form\Type\OroIconType
    oro_form.type.multiple_entity.class:                         Oro\Bundle\FormBundle\Form\Type\MultipleEntityType
    oro_form.type.collection.class:                              Oro\Bundle\FormBundle\Form\Type\CollectionType
    oro_form.type.entity_create_or_select.class:                 Oro\Bundle\FormBundle\Form\Type\OroEntityCreateOrSelectType
    oro_form.type.encoded_password.class:                        Oro\Bundle\FormBundle\Form\Type\OroEncodedPasswordType
    oro_form.type.textlist.class:                                Oro\Bundle\FormBundle\Form\Type\OroTextListType
    oro_form.type.oro_entity_create_or_select_inline.class:      Oro\Bundle\FormBundle\Form\Type\OroEntitySelectOrCreateInlineType
    oro_form.type.link.class:                                    Oro\Bundle\FormBundle\Form\Type\LinkType
    oro_form.type.api.class:                                     Oro\Bundle\FormBundle\Form\Type\AbstractApiType

    oro_form.extension.data_block.class:                         Oro\Bundle\FormBundle\Form\Extension\DataBlockExtension
    oro_form.extension.client_validation.class:                  Oro\Bundle\FormBundle\Form\Extension\ClientValidationExtension
    oro_form.extension.constraint_as_option.class:               Oro\Bundle\FormBundle\Form\Extension\ConstraintAsOptionExtension
    oro_form.extension.tooltip.class:                            Oro\Bundle\FormBundle\Form\Extension\TooltipFormExtension
    oro_form.extension.js_validation.class:                      Oro\Bundle\FormBundle\Form\Extension\JsValidationExtension
    oro_form.extension.js_validation.constraints_provider.class: Oro\Bundle\FormBundle\Form\Extension\JsValidation\ConstraintsProvider
    oro_form.extension.js_validation.repeated.class:             Oro\Bundle\FormBundle\Form\Extension\JsValidation\RepeatedTypeExtension
    oro_form.extension.random_id.class:                          Oro\Bundle\FormBundle\Form\Extension\RandomIdExtension

    oro_form.form_handler.api.class:                             Oro\Bundle\FormBundle\Form\Handler\ApiFormHandler

services:
    # Form types
    oro_form.type.date:
        class: %oro_form.type.date.class%
        tags:
            - { name: form.type, alias: oro_date }

    oro_form.type.datetime:
        class: %oro_form.type.datetime.class%
        arguments:
            - @oro_locale.settings
        tags:
            - { name: form.type, alias: oro_datetime }

    oro_form.type.time_interval:
        class: %oro_form.type.time_interval.class%
        tags:
            - { name: form.type, alias: oro_time_interval }

    oro_form.type.money:
        class: %oro_form.type.money.class%
        arguments:
            - @oro_locale.settings
            - @oro_locale.formatter.number
        tags:
            - { name: form.type, alias: oro_money }

    oro_form.type.percent:
        class: %oro_form.type.percent.class%
        tags:
            - { name: form.type, alias: oro_percent }

    oro_form.type.icon:
        class: %oro_form.type.icon.class%
        tags:
            - { name: form.type, alias: oro_icon_select }

    oro_form.type.entity_identifier:
        class: %oro_form.type.entity_identifier.class%
        arguments: ["@doctrine"]
        tags:
            - { name: form.type, alias: oro_entity_identifier }

    oro_form.type.jqueryselect2_hidden:
        class: %oro_form.type.jqueryselect2_hidden.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_form.autocomplete.search_registry
            - @oro_entity_config.provider.form
        tags:
            - { name: form.type, alias: oro_jqueryselect2_hidden }

    oro_form.type.multiple_entity:
        class: %oro_form.type.multiple_entity.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: oro_multiple_entity }

    oro_form.type.collection:
        class: %oro_form.type.collection.class%
        tags:
             - { name: form.type, alias: oro_collection }

    oro_form.type.entity_create_or_select:
        class: %oro_form.type.entity_create_or_select.class%
        arguments:
            - @oro_entity.doctrine_helper
        tags:
            - { name: form.type, alias: oro_entity_create_or_select }

    # Form extensions
    oro_form.extension.data_block:
        class: %oro_form.extension.data_block.class%
        tags:
            - { name: form.type_extension, alias: form }

    oro_form.extension.client_validation:
        class: %oro_form.extension.client_validation.class%
        tags:
            - { name: form.type_extension, alias: form }

    oro_help.form.tooltip_extension:
        class: %oro_form.extension.tooltip.class%
        tags:
            - { name: form.type_extension, alias: form }

    oro_form.extension.constraint_as_option:
        class: %oro_form.extension.constraint_as_option.class%
        arguments:
            - @oro_form.validator.constraint_factory
        tags:
            - { name: form.type_extension, alias: form }

    oro_form.extension.js_validation:
        class: %oro_form.extension.js_validation.class%
        arguments: [@oro_form.extension.js_validation.constraints_provider]
        tags:
            - { name: form.type_extension, alias: form }

    oro_form.extension.js_validation.constraints_provider:
        class: %oro_form.extension.js_validation.constraints_provider.class%
        arguments:
            - @validator.mapping.class_metadata_factory


    oro_form.extension.js_validation.repeated:
        class: %oro_form.extension.js_validation.repeated.class%
        tags:
            - { name: form.type_extension, alias: repeated }

    oro_form.extension.random_id:
        class: %oro_form.extension.random_id.class%
        tags:
            - { name: form.type_extension, alias: form }

    oro_form.type.encoded_password:
        class: %oro_form.type.encoded_password.class%
        arguments:
            - @oro_security.encoder.mcrypt
        tags:
            - { name: form.type, alias: oro_encoded_password }

    oro_form.type.textlist:
        class: %oro_form.type.textlist.class%
        tags:
            - { name: form.type, alias: oro_textlist }

    oro_form.type.oro_entity_create_or_select_inline:
        class: %oro_form.type.oro_entity_create_or_select_inline.class%
        arguments:
            - @oro_security.security_facade
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type, alias: oro_entity_create_or_select_inline }

    oro_form.type.link:
        class: %oro_form.type.link.class%
        tags:
            - { name: form.type, alias: oro_link_type }

    oro_form.type.api:
        class: %oro_form.type.api.class%
        tags:
            - { name: form.type, alias: oro_api_type }

    oro_form.form_handler.api:
        class: %oro_form.form_handler.api.class%
        scope: request
        arguments:
            - @request
            - @doctrine.orm.entity_manager
