styles:
    inputs:
        - 'bundles/oroform/default/scss/settings/global-settings.scss'
        - 'bundles/oroform/default/scss/variables/button-config.scss'
        - 'bundles/oroform/default/scss/variables/catalog-switcher-config.scss'
        - 'bundles/oroform/default/scss/variables/custom-checkbox-config.scss'
        - 'bundles/oroform/default/scss/variables/custom-radio-config.scss'
        - 'bundles/oroform/default/scss/variables/input-config.scss'
        - 'bundles/oroform/default/scss/variables/select-config.scss'
        - 'bundles/oroform/default/scss/variables/oro-select2-config.scss'
        - 'bundles/oroform/default/scss/variables/oro-toolbar-config.scss'
        - 'bundles/oroform/default/scss/variables/textarea-config.scss'
        - 'bundles/oroform/default/scss/variables/label-config.scss'
        - 'bundles/oroform/default/scss/styles.scss'

stylebook_styles:
    inputs:
        - 'bundles/oroform/default/scss/settings/global-settings.scss'
