services:
    oro_api.update.processor:
        class: Oro\Bundle\ApiBundle\Processor\UpdateProcessor
        public: false
        arguments:
            - '@oro_api.processor_bag'
            - update
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'

    #
    # initialize
    #

    oro_api.update.initialize_config_extras:
        class: Oro\Bundle\ApiBundle\Processor\Update\InitializeConfigExtras
        tags:
            - { name: oro.api.processor, action: update, group: initialize, priority: 10 }

    #
    # resource_check
    #

    #
    # normalize_input
    #

    oro_api.update.json_api.validate_request_data:
        class: Oro\Bundle\ApiBundle\Processor\Update\JsonApi\ValidateRequestData
        arguments:
            - '@oro_api.value_normalizer'
        tags:
            - { name: oro.api.processor, action: update, group: normalize_input, requestType: json_api, priority: 90 }

    oro_api.update.rest.normalize_entity_id:
        class: Oro\Bundle\ApiBundle\Processor\Update\NormalizeEntityId
        arguments:
            - '@oro_api.rest.entity_id_transformer'
        tags:
            - { name: oro.api.processor, action: update, group: normalize_input, requestType: rest, priority: -110 }

    #
    # security_check
    #

    oro_api.update.entity_type_security_check:
        class: Oro\Bundle\ApiBundle\Processor\Shared\EntityTypeSecurityCheck
        arguments:
            - '@oro_api.doctrine_helper'
            - '@security.authorization_checker'
            - EDIT
        tags:
            - { name: oro.api.processor, action: update, group: security_check, priority: 10 }

    # VIEW permissions are required to update an entity because the updated entity should be returned in response
    # the "security_check" group is disabled for the "get" action is executed by
    # the "oro_api.update.load_normalized_entity" processor
    # so, if you add own security processor for the "get" action, add it here as well
    oro_api.update.entity_type_security_check.view:
        class: Oro\Bundle\ApiBundle\Processor\Shared\EntityTypeSecurityCheck
        arguments:
            - '@oro_api.doctrine_helper'
            - '@security.authorization_checker'
            - VIEW
            - true
        tags:
            - { name: oro.api.processor, action: update, group: security_check, priority: 5 }

    #
    # build_query
    #

    oro_api.update.protect_query_by_acl:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ProtectQueryByAcl
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_security.acl_helper'
            - '@oro_security.acl.annotation_provider'
            - EDIT
        tags:
            - { name: oro.api.processor, action: update, group: build_query, priority: -90 }

    #
    # load_data
    #

    #
    # transform_data
    #

    oro_api.update.build_form_builder:
        class: Oro\Bundle\ApiBundle\Processor\Shared\BuildFormBuilder
        arguments:
            - '@oro_api.form_helper'
        tags:
            - { name: oro.api.processor, action: update, group: transform_data, priority: 100 }

    oro_api.update.submit_form:
        class: Oro\Bundle\ApiBundle\Processor\Shared\SubmitForm
        tags:
            - { name: oro.api.processor, action: update, group: transform_data, priority: -50 }

    #
    # save_data
    #

    oro_api.update.save_entity:
        class: Oro\Bundle\ApiBundle\Processor\Update\SaveEntity
        arguments:
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: update, group: save_data, priority: -10 }

    #
    # normalize_data
    #

    oro_api.update.load_normalized_entity:
        class: Oro\Bundle\ApiBundle\Processor\Shared\LoadNormalizedEntity
        arguments:
            - '@oro_api.action_processor_bag'
        tags:
            - { name: oro.api.processor, action: update, group: normalize_data, priority: -10 }

    #
    # normalize_result
    #
