services:
    oro_api.delete.processor:
        class: Oro\Bundle\ApiBundle\Processor\DeleteProcessor
        public: false
        arguments:
            - '@oro_api.processor_bag'
            - delete
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'

    #
    # initialize
    #

    oro_api.delete.initialize_config_extras:
        class: Oro\Bundle\ApiBundle\Processor\Delete\InitializeConfigExtras
        tags:
            - { name: oro.api.processor, action: delete, group: initialize, priority: 10 }

    #
    # resource_check
    #

    #
    # normalize_input
    #

    #
    # security_check
    #

    oro_api.delete.entity_type_security_check:
        class: Oro\Bundle\ApiBundle\Processor\Shared\EntityTypeSecurityCheck
        arguments:
            - '@oro_api.doctrine_helper'
            - '@security.authorization_checker'
            - DELETE
        tags:
            - { name: oro.api.processor, action: delete, group: security_check, priority: 10 }

    #
    # build_query
    #

    oro_api.delete.protect_query_by_acl:
        class: Oro\Bundle\ApiBundle\Processor\Shared\ProtectQueryByAcl
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_security.acl_helper'
            - '@oro_security.acl.annotation_provider'
            - DELETE
        tags:
            - { name: oro.api.processor, action: delete, group: build_query, priority: -90 }

    #
    # load_data
    #

    oro_api.delete.validate_loaded_result:
        class: Oro\Bundle\ApiBundle\Processor\Delete\ValidateLoadedResult
        tags:
            - { name: oro.api.processor, action: delete, group: load_data, priority: -200 }

    #
    # delete_data
    #

    oro_api.delete.delete_data_by_handler:
        class: Oro\Bundle\ApiBundle\Processor\Delete\DeleteDataByDeleteHandler
        arguments:
            - '@oro_api.doctrine_helper'
            - '@service_container'
        tags:
            - { name: oro.api.processor, action: delete, group: delete_data, priority: -10 }

    oro_api.delete.validate_deletion_result:
        class: Oro\Bundle\ApiBundle\Processor\Delete\ValidateDeletionResult
        tags:
            - { name: oro.api.processor, action: delete, group: delete_data, priority: -200 }

    #
    # normalize_result
    #
