services:
    oro_api.get_subresource.processor:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\GetSubresourceProcessor
        public: false
        arguments:
            - '@oro_api.processor_bag'
            - get_subresource
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'

    #
    # initialize
    #

    oro_api.get_subresource.initialize_config_extras:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\GetSubresource\InitializeConfigExtras
        tags:
            - { name: oro.api.processor, action: get_subresource, group: initialize, priority: 10 }

    #
    # resource_check
    #

    #
    # normalize_input
    #

    #
    # security_check
    #

    oro_api.get_subresource.parent_entity_type_security_check:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\Shared\ParentEntityTypeSecurityCheck
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_security.security_facade'
            - VIEW
        tags:
            - { name: oro.api.processor, action: get_subresource, group: security_check, priority: 10 }

    #
    # build_query
    #

    #
    # load_data
    #

    oro_api.get_subresource.load_extended_association:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\GetSubresource\LoadExtendedAssociation
        arguments:
            - '@oro_api.entity_serializer'
            - '@oro_api.doctrine_helper'
            - '@oro_entity_extend.association_manager'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: load_data }

    oro_api.get_subresource.load_nested_association:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\GetSubresource\LoadNestedAssociation
        arguments:
            - '@oro_api.entity_serializer'
            - '@oro_api.doctrine_helper'
            - '@oro_api.entity_title_provider'
        tags:
            - { name: oro.api.processor, action: get_subresource, group: load_data, collection: false }

    #
    # normalize_data
    #

    #
    # finalize
    #

    #
    # normalize_result
    #
