services:
    oro_api.get_relationship.processor:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\GetRelationshipProcessor
        public: false
        arguments:
            - '@oro_api.processor_bag'
            - get_relationship
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'

    #
    # initialize
    #

    oro_api.get_relationship.initialize_config_extras:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\GetRelationship\InitializeConfigExtras
        tags:
            - { name: oro.api.processor, action: get_relationship, group: initialize, priority: 10 }

    #
    # resource_check
    #

    #
    # normalize_input
    #

    #
    # security_check
    #

    oro_api.get_relationship.parent_entity_type_security_check:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\Shared\ParentEntityTypeSecurityCheck
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_security.security_facade'
            - VIEW
        tags:
            - { name: oro.api.processor, action: get_relationship, group: security_check, priority: 10 }

    #
    # build_query
    #

    #
    # load_data
    #

    oro_api.get_relationship.load_extended_association:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\Shared\LoadExtendedAssociation
        arguments:
            - '@oro_api.entity_serializer'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: get_relationship, group: load_data }

    oro_api.get_relationship.load_nested_association:
        class: Oro\Bundle\ApiBundle\Processor\Subresource\Shared\LoadNestedAssociation
        arguments:
            - '@oro_api.entity_serializer'
            - '@oro_api.doctrine_helper'
        tags:
            - { name: oro.api.processor, action: get_relationship, group: load_data, collection: false }

    #
    # normalize_data
    #

    #
    # finalize
    #

    #
    # normalize_result
    #
