app-modules:
    - orosync/js/app/modules/content-manager-module
dynamic-imports:
    commons:
        - orosync/js/content-manager
        - orosync/js/content/grid-builder
        - orosync/js/sync
