parameters:
    oro_organization.form.type.organization_select.class:    Oro\Bundle\OrganizationBundle\Form\Type\OrganizationSelectType

services:
    oro_organization.form.type.organization_select:
        class: %oro_organization.form.type.organization_select.class%
        tags:
            - { name: form.type, alias: oro_organization_select }
