oro_system_configuration:
    fields:
        oro_navigation.maxItems:
            type: integer
        oro_navigation.title_suffix:
            type: text
        oro_navigation.title_delimiter:
            type: text
        oro_navigation.breadcrumb_menu:
            type: text

    tree:
        look-and-feel:
            oro_navigation.maxItems: ~
            oro_navigation.title_suffix: ~
            oro_navigation.title_delimiter: ~
            oro_navigation.breadcrumb_menu: ~
