parameters:
    oro_sidebar.entity.sidebar_state.class: Oro\Bundle\SidebarBundle\Entity\SidebarState
    oro_sidebar.entity.widget.class: Oro\Bundle\SidebarBundle\Entity\Widget

    oro_sidebar.widget_definition.registry.class: Oro\Bundle\SidebarBundle\Model\WidgetDefinitionRegistry

services:
    oro_sidebar.widget_definition.registry:
        class: %oro_sidebar.widget_definition.registry.class%
        arguments:
            - %oro_sidebar.sidebar_widgets_definitions%

    oro_sidebar.twig.extension:
        class: Oro\Bundle\SidebarBundle\Twig\SidebarExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }
            - { name: oro_featuretogle.feature, feature: email }

    oro_sidebar.request.handler:
        class: Oro\Bundle\SidebarBundle\EventListener\RequestHandler
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    oro_sidebar.config_extension.feature:
        class: 'Oro\Bundle\SidebarBundle\Configuration\FeatureConfigurationExtension'
        tags:
            - { name: oro_feature.config_extension }
