config:
    shim:
        'jquery.uniform':
            deps:
                - 'jquery'
        'jquery.select2':
            deps:
                - 'jquery'
            exports: 'Select2'
        'jquery.simplecolorpicker':
            deps:
                - 'jquery'
        'jquery.minicolors':
            deps:
                - 'jquery'
        'jquery.datepair':
            deps:
                - 'jquery'
                - 'datepair'
        'jquery.multiselect':
            deps:
                - 'jquery-ui'
        'jquery.multiselect.filter':
            deps:
                - 'jquery.multiselect'
        'jquery.form':
            deps:
                - 'jquery'
        'lightgallery':
            deps:
                - 'jquery'
        'lightgallery.print':
            deps:
                - 'lightgallery'
                - 'jquery'
        'bootstrap-typeahead':
            deps:
                - 'jquery'
    map:
        '*':
            'jquery': 'oroui/js/extend/jquery'
            'jquery.select2': 'oroui/js/extend/select2'
            'jquery.multiselect': 'oroui/js/extend/jquery.multiselect'
            'jquery.multiselect.filter': 'oroui/js/extend/jquery.multiselect-filter'
            'jquery.uniform': 'oroui/js/extend/jquery.uniform'
            'chaplin': 'oroui/js/extend/chaplin'
            'underscore': 'oroui/js/extend/underscore'
            'backbone': 'oroui/js/extend/backbone'
            'bootstrap': 'oroui/js/extend/bootstrap'
            'jquery-ui': 'oroui/js/jquery-ui-datepicker-l10n'
            'jquery.timepicker': 'oroui/js/extend/jquery.timepicker'
            'popper.js': 'popper'
            'util.js': 'bootstrap-util'
            'alert.js': 'bootstrap-alert'
            'collapse.js': 'bootstrap-collapse'
            'dropdown.js': 'bootstrap-dropdown'
            'modal.js': 'bootstrap-modal'
            'popover.js': 'bootstrap-popover'
            'scrollspy.js': 'bootstrap-scrollspy'
            'tab.js': 'bootstrap-tab'
            'tooltip.js': 'bootstrap-tooltip'
        'oroui/js/extend/jquery':
            'jquery': 'jquery'
        'oroui/js/extend/select2':
            'jquery.select2': 'jquery.select2'
        'oroui/js/select2-l10n':
            'jquery.select2': 'jquery.select2'
        'oroui/js/extend/jquery.multiselect':
            'jquery.multiselect': 'jquery.multiselect'
        'oroui/js/extend/jquery.multiselect-filter':
            'jquery.multiselect.filter': 'jquery.multiselect.filter'
        'oroui/js/extend/jquery.uniform':
            'jquery.uniform': 'jquery.uniform'
        'oroui/js/extend/jquery-ui':
            'jquery-ui': 'jquery-ui'
        'oroui/js/extend/chaplin':
            'chaplin': 'chaplin'
        'oroui/js/extend/underscore':
            'underscore': 'underscore'
        'oroui/js/extend/backbone':
            'backbone': 'backbone'
        'oroui/js/extend/bootstrap':
            'bootstrap': 'bootstrap'
        'oroui/js/jquery-ui-datepicker-l10n':
            'jquery-ui': 'oroui/js/extend/jquery-ui'
        'oroui/js/jquery-timepicker-l10n':
            'jquery.timepicker': 'jquery.timepicker'
        'oroui/js/extend/jquery.timepicker':
            'jquery.timepicker': 'jquery.timepicker'
        'chaplin':
            'backbone': 'backbone'
        'oroui/js/app/components/base/component':
            'backbone': 'backbone'
            'chaplin': 'chaplin'
        'oroui/js/mediator':
            'chaplin': 'chaplin'
        'oroui/js/tools':
            'chaplin': 'chaplin'
    paths:
        'text': 'bundles/bowerassets/text/text.js'
        'base64': 'oroui/js/extend/base64.js'
        'jquery': 'bundles/npmassets/jquery/dist/jquery.js'
        'jquery-ui': 'bundles/oroui/lib/jquery-ui.js'
        'jquery.form': 'bundles/bowerassets/jquery-form/src/jquery.form.js'
        'jquery.mousewheel': 'bundles/bowerassets/jquery-mousewheel/jquery.mousewheel.js'
        'jquery.numeric': 'bundles/bowerassets/jquery.numeric/jquery.numeric.js'
        'jquery.uniform': 'bundles/npmassets/jquery.uniform/src/js/jquery.uniform.js'
        'jquery.select2': 'bundles/bowerassets/select2/select2.js'
        'jquery.multiselect': 'bundles/bowerassets/jquery-ui-multiselect-widget/src/jquery.multiselect.min.js'
        'jquery.multiselect.filter': 'bundles/bowerassets/jquery-ui-multiselect-widget/src/jquery.multiselect.filter.min.js'
        'jquery.simplecolorpicker': 'bundles/oroui/lib/simplecolorpicker/jquery.simplecolorpicker.js'
        'jquery.minicolors': 'bundles/oroui/lib/minicolors/jquery.minicolors.js'
        'jquery.cookie': 'bundles/bowerassets/jquery-cookie/jquery.cookie.js'
        'overlayScrollbars': 'bundles/npmassets/overlayscrollbars/js/OverlayScrollbars.js'
        'styled-scroll-bar': 'bundles/oroui/js/app/plugins/styled-scroll-bar.js'
        'jquery.jstree': 'bundles/bowerassets/jstree/dist/jstree.js'
        'popper': 'bundles/npmassets/popper.js/dist/umd/popper.js'
        'bootstrap-util': 'bundles/npmassets/bootstrap/js/dist/util.js'
        'bootstrap-alert': 'bundles/npmassets/bootstrap/js/dist/alert.js'
        'bootstrap-collapse': 'bundles/npmassets/bootstrap/js/dist/collapse.js'
        'bootstrap-dropdown': 'bundles/npmassets/bootstrap/js/dist/dropdown.js'
        'bootstrap-modal': 'bundles/npmassets/bootstrap/js/dist/modal.js'
        'bootstrap-popover': 'bundles/npmassets/bootstrap/js/dist/popover.js'
        'bootstrap-scrollspy': 'bundles/npmassets/bootstrap/js/dist/scrollspy.js'
        'bootstrap-tab': 'bundles/npmassets/bootstrap/js/dist/tab.js'
        'bootstrap-tooltip': 'bundles/npmassets/bootstrap/js/dist/tooltip.js'
        'bootstrap-typeahead': 'bundles/oroui/lib/bootstrap/bootstrap-typeahead.js'
        'bootstrap': 'bundles/oroui/lib/bootstrap.js'
        'underscore': 'bundles/npmassets/underscore/underscore.js'
        'backbone': 'bundles/npmassets/backbone/backbone.js'
        'chaplin': 'bundles/bowerassets/chaplin/chaplin.js'
        'jquery.timepicker': 'bundles/bowerassets/timepicker/jquery.timepicker.js'
        'jquery.datepair': 'bundles/bowerassets/datepair/dist/jquery.datepair.js'
        'datepair': 'bundles/bowerassets/datepair/dist/datepair.js'
        'cryptojs/core': 'bundles/bowerassets/crypto-js/core.js'
        'cryptojs/enc-base64': 'bundles/bowerassets/crypto-js/enc-base64.js'
        'cryptojs/pbkdf2': 'bundles/bowerassets/crypto-js/pbkdf2.js'
        'cryptojs/hmac-sha256': 'bundles/bowerassets/crypto-js/hmac-sha256.js'
        'cryptojs/sha1': 'bundles/bowerassets/crypto-js/sha1.js'
        'cryptojs/hmac': 'bundles/bowerassets/crypto-js/hmac.js'
        'cryptojs/sha256': 'bundles/bowerassets/crypto-js/sha256.js'
        'lightgallery': 'bundles/bowerassets/lightgallery/dist/js/lightgallery.js'
        'lightgallery.print': 'bundles/oroui/js/lightgallery/lg-print.js'

        'ready': 'bundles/oroui/js/requirejs/ready.js'
        'tpl': 'bundles/oroui/js/requirejs/tpl.js'
        'oroui/js/tools/api-accessor': 'bundles/oroui/js/tools/api-accessor.js'
        'oroui/js/tools/search-api-accessor': 'bundles/oroui/js/tools/search-api-accessor.js'
        'oroui/js/tools/layout-helper': 'bundles/oroui/js/tools/layout-helper.js'
        'oroui/js/app/ready-state-tracker': 'bundles/oroui/js/app/ready-state-tracker.js'
        'controllers/page-controller': 'bundles/oroui/js/app/controllers/page-controller.js'
        'oroui/js/app/modules/layout-module': 'bundles/oroui/js/app/modules/layout-module.js'
        'oroui/js/app/modules/messenger-module': 'bundles/oroui/js/app/modules/messenger-module.js'
        'oroui/js/app/modules/widgets-module': 'bundles/oroui/js/app/modules/widgets-module.js'
        'oroui/js/app/modules/input-widgets': 'bundles/oroui/js/app/modules/input-widgets.js'
        'oroui/js/app/modules/viewport-module': 'bundles/oroui/js/app/modules/viewport-module.js'
        'oroui/js/app/modules/ajax-error-module': 'bundles/oroui/js/app/modules/ajax-error-module.js'
        'oroui/js/app/modules/jstree-actions-module': 'bundles/oroui/js/app/modules/jstree-actions-module.js'
        'oroui/js/app/modules/init-layout': 'bundles/oroui/js/app/modules/init-layout.js'
        'oroui/js/app/modules/init-lightgallery': 'bundles/oroui/js/app/modules/init-lightgallery.js'
        'oroui/js/app/modules/component-shortcuts-module': 'bundles/oroui/js/app/modules/component-shortcuts-module.js'
        'oroui/js/app/modules/resizable-area-module': 'bundles/oroui/js/app/modules/resizable-area-module.js'
        'oroui/js/app/modules/responsive-layout-module': 'bundles/oroui/js/app/modules/responsive-layout-module.js'
        'oroui/js/app/modules/styled-scroll-bar-module': 'bundles/oroui/js/app/modules/styled-scroll-bar-module.js'
        'oroui/js/app/modules/color-util': 'bundles/oroui/js/app/modules/color-util.js'
        'oroui/js/app/application': 'bundles/oroui/js/app/application.js'
        'oroui/js/app/routes': 'bundles/oroui/js/app/routes.js'
        'oroui/js/app/services/registry': 'bundles/oroui/js/app/services/registry.js'
        'oroui/js/app/models/base/collection': 'bundles/oroui/js/app/models/base/collection.js'
        'oroui/js/app/models/sync-machine-proxy-cache': 'bundles/oroui/js/app/models/sync-machine-proxy-cache.js'
        'oroui/js/app/views/hidden-initialization-view': 'bundles/oroui/js/app/views/hidden-initialization-view.js'
        'oroui/js/app/views/page-center-title-view': 'bundles/oroui/js/app/views/page-center-title-view.js'
        'oroui/js/app/views/page/before-content-addition-view': 'bundles/oroui/js/app/views/page/before-content-addition-view.js'
        'oroui/js/app/views/page/breadcrumb-view': 'bundles/oroui/js/app/views/page/breadcrumb-view.js'
        'oroui/js/app/views/page/content-view': 'bundles/oroui/js/app/views/page/content-view.js'
        'oroui/js/app/views/page/main-menu-view': 'bundles/oroui/js/app/views/page/main-menu-view.js'
        'oroui/js/app/views/page/organization-switch-view': 'bundles/oroui/js/app/views/page/organization-switch-view.js'
        'oroui/js/app/views/page/user-menu-view': 'bundles/oroui/js/app/views/page/user-menu-view.js'
        'oroui/js/app/views/page/messages-view': 'bundles/oroui/js/app/views/page/messages-view.js'
        'oroui/js/app/views/page/debug-toolbar-view': 'bundles/oroui/js/app/views/page/debug-toolbar-view.js'
        'oroui/js/app/views/datepicker/datetimepicker-view': 'bundles/oroui/js/app/views/datepicker/datetimepicker-view.js'
        'oroui/js/app/views/datepicker/datepicker-view': 'bundles/oroui/js/app/views/datepicker/datepicker-view.js'
        'oroui/js/app/views/zoomable-area-view': 'bundles/oroui/js/app/views/zoomable-area-view.js'
        'oroui/js/app/views/tab-collection-view': 'bundles/oroui/js/app/views/tab-collection-view.js'
        'oroui/js/app/views/content-sidebar-view': 'bundles/oroui/js/app/views/content-sidebar-view.js'
        'oroui/js/app/views/highlight-text-view': 'bundles/oroui/js/app/views/highlight-text-view.js'
        'oroui/js/app/views/swipeable-view': 'bundles/oroui/js/app/views/swipeable-view.js'

        'oroui/js/app/plugins/plugin-resizable-area': 'bundles/oroui/js/app/plugins/plugin-resizable-area.js'

        'oroui/js/viewport-manager': 'bundles/oroui/js/viewport-manager.js'
        'oroui/js/delete-confirmation': 'bundles/oroui/js/delete-confirmation.js'
        'oroui/js/standard-confirmation': 'bundles/oroui/js/standard-confirmation.js'
        'oroui/js/error': 'bundles/oroui/js/error.js'
        'oroui/js/layout': 'bundles/oroui/js/layout.js'
        'oroui/js/mediator': 'bundles/oroui/js/mediator.js'
        'oroui/js/tools': 'bundles/oroui/js/tools.js'
        'oroui/js/messenger': 'bundles/oroui/js/messenger.js'
        'oroui/js/modal': 'bundles/oroui/js/modal.js'
        'oroui/js/scrollspy': 'bundles/oroui/js/scrollspy.js'
        'oroui/js/drag-n-drop-sorting': 'bundles/oroui/js/drag-n-drop-sorting.js'

        'oroui/js/extend/jquery': 'bundles/oroui/js/extend/jquery.js'
        'oroui/js/extend/underscore': 'bundles/oroui/js/extend/underscore.js'
        'oroui/js/extend/jquery.uniform': 'bundles/oroui/js/extend/jquery.uniform.js'

        'oroui/js/app/components/app-loading-mask-component': 'bundles/oroui/js/app/components/app-loading-mask-component.js'
        'oroui/js/app/components/app-loading-bar-component': 'bundles/oroui/js/app/components/app-loading-bar-component.js'
        'oroui/js/app/components/ajax-button': 'bundles/oroui/js/app/components/ajax-button.js'
        'oroui/js/app/components/hidden-redirect-component': 'bundles/oroui/js/app/components/hidden-redirect-component.js'
        'oroui/js/app/components/jquery-widget-component': 'bundles/oroui/js/app/components/jquery-widget-component.js'
        'oroui/js/app/components/tabs-component': 'bundles/oroui/js/app/components/tabs-component.js'
        'oroui/js/app/components/view-component': 'bundles/oroui/js/app/components/view-component.js'
        'oroui/js/app/components/viewport-component': 'bundles/oroui/js/app/components/viewport-component.js'
        'oroui/js/app/components/widget-component': 'bundles/oroui/js/app/components/widget-component.js'
        'oroui/js/app/components/widget-form-component': 'bundles/oroui/js/app/components/widget-form-component.js'
        'oroui/js/app/views/jstree/base-tree-view': 'bundles/oroui/js/app/views/jstree/base-tree-view.js'
        'oroui/js/app/views/jstree/base-tree-manage-view': 'bundles/oroui/js/app/views/jstree/base-tree-manage-view.js'
        'oroui/js/app/views/sticky-element/sticky-element-mixin': 'bundles/oroui/js/app/views/sticky-element/sticky-element-mixin.js'
        'oroui/js/app/views/sticky-element/sticky-element-view': 'bundles/oroui/js/app/views/sticky-element/sticky-element-view.js'
        'oroui/js/app/components/widget-picker-component': 'bundles/oroui/js/app/components/widget-picker-component.js'
        'oroui/js/app/views/element-value-copy-to-clipboard-view': 'bundles/oroui/js/app/views/element-value-copy-to-clipboard-view.js'
        'oroui/js/widget-manager': 'bundles/oroui/js/widget/widget-manager.js'
        'oroui/js/widget/abstract-widget': 'bundles/oroui/js/widget/abstract-widget.js'
        'oroui/js/widget/collapse-widget': 'bundles/oroui/js/widget/collapse-widget.js'
        'oroui/js/widget/collapse-group-widget': 'bundles/oroui/js/widget/collapse-group-widget.js'
        'oro/block-widget': 'bundles/oroui/js/widget/block-widget.js'
        'oro/page-widget': 'bundles/oroui/js/widget/page-widget.js'
        'oro/buttons-widget': 'bundles/oroui/js/widget/buttons-widget.js'
        'oroui/js/mobile/layout': 'bundles/oroui/js/mobile/layout.js'
        'oroui/js/mobile/page-header': 'bundles/oroui/js/mobile/page-header.js'
        'oroui/js/mobile/side-menu': 'bundles/oroui/js/mobile/side-menu.js'

        'oroui/js/desktop/side-menu': 'bundles/oroui/js/desktop/side-menu.js'
        'oroui/js/desktop/side-menu-overlay': 'bundles/oroui/js/desktop/side-menu-overlay.js'

        'oroui/js/items-manager/table': 'bundles/oroui/js/items-manager/table.js'
        'oroui/js/items-manager/editor': 'bundles/oroui/js/items-manager/editor.js'

        'oroui/js/jstree-action-manager': 'bundles/oroui/js/jstree-action-manager.js'
        'oroui/js/input-widget-manager': 'bundles/oroui/js/input-widget-manager.js'
        'oroui/js/app/views/input-widget/abstract': 'bundles/oroui/js/app/views/input-widget/abstract.js'
        'oroui/js/app/views/input-widget/uniform-file': 'bundles/oroui/js/app/views/input-widget/uniform-file.js'
        'oroui/js/app/views/input-widget/uniform-select': 'bundles/oroui/js/app/views/input-widget/uniform-select.js'
        'oroui/js/app/views/input-widget/checkbox': 'bundles/oroui/js/app/views/input-widget/checkbox.js'
        'oroui/js/app/views/input-widget/select2': 'bundles/oroui/js/app/views/input-widget/select2.js'
        'oroui/js/app/views/input-widget/number': 'bundles/oroui/js/app/views/input-widget/number.js'

        'oroui/js/fuzzy-search': 'bundles/oroui/js/fuzzy-search.js'
        'Fuse': 'bundles/bowerassets/fuse/dist/fuse.js'

        'oroui/js/content-processor/pinned-dropdown-button': 'oroui/js/content-processor/pinned-dropdown-button.js'

        'oroui/js/app/views/widget-picker/widget-picker-collection-view': 'bundles/oroui/js/app/views/widget-picker/widget-picker-collection-view.js'
        'oroui/js/app/views/widget-picker/widget-picker-filter-view': 'bundles/oroui/js/app/views/widget-picker/widget-picker-filter-view.js'
        'oroui/js/app/views/widget-picker/widget-picker-item-view': 'bundles/oroui/js/app/views/widget-picker/widget-picker-item-view.js'
        'oroui/js/app/models/widget-picker/widget-picker-filter-model': 'bundles/oroui/js/app/models/widget-picker/widget-picker-filter-model.js'
        'oroui/js/app/models/widget-picker/widget-picker-model': 'bundles/oroui/js/app/models/widget-picker/widget-picker-model.js'

        'autolinker': 'bundles/bowerassets/autolinker.js/dist/Autolinker.js'

        'oroui/js/extend/polyfill': 'oroui/js/extend/polyfill'

        'oroui/js/app/views/jstree/action-manager-view': 'bundles/oroui/js/app/views/jstree/action-manager-view.js'
        'oroui/js/app/views/jstree/abstract-action-view': 'bundles/oroui/js/app/views/jstree/abstract-action-view.js'
        'oroui/js/app/views/jstree/expand-action-view': 'bundles/oroui/js/app/views/jstree/expand-action-view.js'
        'oroui/js/app/views/jstree/collapse-action-view': 'bundles/oroui/js/app/views/jstree/collapse-action-view.js'
        'oroui/js/app/views/jstree/subtree-action-view': 'bundles/oroui/js/app/views/jstree/subtree-action-view.js'
        'oroui/js/app/views/jstree/move-action-view': 'bundles/oroui/js/app/views/jstree/move-action-view.js'
        'oroui/js/app/views/loading-bar-view': 'bundles/oroui/js/app/views/loading-bar-view.js'

    appmodules:
        - oroui/js/app/modules/init-layout
        - oroui/js/app/modules/init-lightgallery
        - oroui/js/app/modules/layout-module
        - oroui/js/app/modules/messenger-module
        - oroui/js/app/modules/widgets-module
        - oroui/js/app/modules/ajax-error-module
        - oroui/js/app/modules/input-widgets
        - oroui/js/app/modules/jstree-actions-module
        - oroui/js/app/modules/component-shortcuts-module
        - oroui/js/app/modules/viewport-module
        - oroui/js/app/modules/resizable-area-module
        - oroui/js/app/modules/responsive-layout-module
        - oroui/js/app/modules/styled-scroll-bar-module
        - oroui/js/app/modules/color-util

build:
    paths:
#       jQuery.UI after v.1.11.2 started to support AMD. And that broke a js-build with
#       files which does not support AMD. jquery.multiselect and jquery.multiselect.filter
#       use AMD without dependency, therefore it's excluded
        'jquery.multiselect': 'empty:'
        'jquery.multiselect.filter': 'empty:'
