parameters:
    oro_datagrid.datagrid.base.class:                       Oro\Bundle\DataGridBundle\Datagrid\Datagrid
    oro_datagrid.extension.acceptor.class:                  Oro\Bundle\DataGridBundle\Extension\Acceptor

    oro_datagrid.datagrid.manager.class:                    Oro\Bundle\DataGridBundle\Datagrid\Manager
    oro_datagrid.datagrid.builder.class:                    Oro\Bundle\DataGridBundle\Datagrid\Builder
    oro_datagrid.datagrid.parameters.class:                 Oro\Bundle\DataGridBundle\Datagrid\ParameterBag
    oro_datagrid.datagrid.request_parameters_factory.class: Oro\Bundle\DataGridBundle\Datagrid\RequestParameterBagFactory

    oro_datagrid.provider.resolver.class:                   Oro\Bundle\DataGridBundle\Provider\SystemAwareResolver

    oro_datagrid.twig.datagrid.class:                       Oro\Bundle\DataGridBundle\Twig\DataGridExtension
    oro_datagrid.event_listener.base_orm_relation.class:    Oro\Bundle\DataGridBundle\EventListener\BaseOrmRelationDatagridListener
    oro_datagrid.configuration.provider.class:              Oro\Bundle\DataGridBundle\Provider\ConfigurationProvider
    oro_datagrid.configuration.provider.chain.class:        Oro\Bundle\DataGridBundle\Provider\ChainConfigurationProvider
    oro_datagrid.event.dispatcher.class:             Oro\Bundle\DataGridBundle\Event\EventDispatcher
    oro_datagrid.event_listener.ormdatasource_acl.class:    Oro\Bundle\DataGridBundle\EventListener\OrmDatasourceAclListener
    oro_datagrid.event_listener.hide_toolbar_by_records.class: Oro\Bundle\DataGridBundle\EventListener\DisableToolbarByRecordCountListener

services:
    oro_datagrid.datagrid.manager:
        class: %oro_datagrid.datagrid.manager.class%
        arguments:
            - @oro_datagrid.configuration.provider.chain
            - @oro_datagrid.datagrid.builder
            - @oro_datagrid.datagrid.request_parameters_factory

    oro_datagrid.datagrid.manager.link:
        tags:
            - { name: oro_service_link,  service: oro_datagrid.datagrid.manager }

    oro_datagrid.event.dispatcher:
        class: %oro_datagrid.event.dispatcher.class%
        arguments: [@event_dispatcher]

    oro_datagrid.datagrid.builder:
        class: %oro_datagrid.datagrid.builder.class%
        arguments:
            - %oro_datagrid.datagrid.base.class%
            - %oro_datagrid.extension.acceptor.class%
            - @oro_datagrid.event.dispatcher
        lazy: true

    oro_datagrid.datagrid.request_parameters_factory:
        class: %oro_datagrid.datagrid.request_parameters_factory.class%
        arguments:
            - %oro_datagrid.datagrid.parameters.class%
        calls:
            - [setRequest, [@?request=]]

    oro_datagrid.provider.resolver:
        class: %oro_datagrid.provider.resolver.class%
        arguments:
            - @service_container

    oro_datagrid.configuration.provider:
        class: %oro_datagrid.configuration.provider.class%
        arguments:
            - []
            - @oro_datagrid.provider.resolver
        tags:
            - { name: oro_datagrid.configuration.provider, priority: -10 }

    oro_datagrid.configuration.provider.chain:
        class: %oro_datagrid.configuration.provider.chain.class%

    oro_datagrid.twig.datagrid:
        class: %oro_datagrid.twig.datagrid.class%
        arguments:
            - @oro_datagrid.datagrid.manager
            - @router
            - @oro_security.security_facade
        tags:
            - { name: twig.extension }

    oro_datagrid.event_listener.ormdatasource_acl:
        class: %oro_datagrid.event_listener.ormdatasource_acl.class%
        arguments:
            - @oro_security.acl_helper
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.before, method: onResultBefore }
