parameters:
    oro.embedded_form.form_type.available_form.class:        Oro\Bundle\EmbeddedFormBundle\Form\Type\AvailableEmbeddedFormType
    oro_embedded_form.manager.class:                         Oro\Bundle\EmbeddedFormBundle\Manager\EmbeddedFormManager
    oro_embedded_form.back_link.twig.extension.class:        Oro\Bundle\EmbeddedFormBundle\Twig\BackLinkExtension
    oro_embedded_form.form_type.class:                       Oro\Bundle\EmbeddedFormBundle\Form\Type\EmbeddedFormType
services:
    oro_embedded_form.form_type.available_embedded_form:
        class: %oro.embedded_form.form_type.available_form.class%
        arguments:
            - @oro_embedded_form.manager
        tags:
            - { name: form.type, alias: oro_available_embedded_forms }

    oro_embedded_form.manager:
        class: %oro_embedded_form.manager.class%
        arguments:
            - @service_container
            - @form.factory

    oro_embedded_form.back_link.twig.extension:
        class: %oro_embedded_form.back_link.twig.extension.class%
        arguments:
            - @router
            - @translator
        tags:
            - { name: twig.extension }

    oro_embedded_form.form_type:
        class: %oro_embedded_form.form_type.class%
        tags:
            - { name: form.type, alias: embedded_form }
