datagrid:
    tag-grid:
#        inline_editing:
#            enable: true
#            entity_name: Oro\Bundle\TagBundle\Entity\Tag
#            behaviour: enable_all
#            plugin: orodatagrid/js/app/plugins/grid/inline-editing-plugin
#            default_editors: orodatagrid/js/default-editors
#
#            save_api_accessor:
#                # api accessor options
#
#        options:
#            entityHint: tag
#            entity_pagination: true
#
        acl_resource: oro_tag_view
        source:
            type: orm
            query:
                select:
                    - t.id
                    - t.name
                    - COUNT(tt.id) as usage
                    - ta.name as taxonomyName
                    - IDENTITY(t.taxonomy) as taxonomy
                from:
                    - { table: OroTagBundle:Tag, alias: t }
                join:
                    left:
                        taxonomy:
                            join: t.taxonomy
                            alias: ta
                        tagging:
                            join: t.tagging
                            alias: tt
                groupBy: t.id

        columns:
            name:
                label: oro.tag.name.label
                type: field
                frontend_type: string
            taxonomyName:
                label: oro.taxonomy.label
                type: field
                frontend_type: string
#                editable: true
#                frontend_type: relation
#                editable: true # this cell will be editable
#                expanded: true # this cell will be rendered as radio buttons
#                inline_editing:
#                    enable: true
#                    editor:
#                        view: oroform/js/app/views/editor/related-id-relation-editor-view
#                    autocomplete_api_accessor:
#                        class: oroui/js/tools/search-api-accessor

            backgroundColor:
                label: oro.taxonomy.background_color.label
                type: field
                frontend_type: string
            usage:
                label: oro.tag.datagrid.usage_count
                type: field
                frontend_type: integer
        properties:
            id: ~
            update_link:
                type: url
                route: oro_tag_update
                params:
                    - id
            search_link:
                type: url
                route: oro_tag_search
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_tag
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: t.name
                usage:
                    data_name: usage
                taxonomyName:
                    data_name: tagTaxonomy.name
            default:
                name: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

        filters:
            columns:
                name:
                    type: string
                    data_name: t.name
                usage:
                    type: number-range
                    data_name: usage
                    filter_by_having: true
                taxonomyName:
                        type: entity
                        data_name: t.taxonomy
                        enabled: true
                        options:
                            field_options:
                                class: OroTagBundle:Taxonomy
                                property: name
                                translatable_options: false
        actions:
            search:
                type:          navigate
                label:         oro.tag.datagrid.search
                link:          search_link
                icon:          search
                acl_resource:  oro_tag_view
                rowAction:     true
            update:
                type:          navigate
                label:         oro.grid.action.update
                link:          update_link
                icon:          edit
                acl_resource:  oro_tag_update
            delete:
                type:          delete
                label:         oro.grid.action.delete
                link:          delete_link
                icon:          trash
                acl_resource:  oro_tag_delete


    tag-results-grid:
        options:
            entityHint: result
        acl_resource: oro_tag_view
        source:
            type: orm
            query:
                select:
                    - tt.entityName
                    - tt.recordId
                from:
                    - { table: OroTagBundle:Tagging, alias: tt }
                groupBy: tt.entityName, tt.recordId
                where:
                    and:
                        - tt.tag = :tag
        columns:
            entity:
                label: Item
                type: tag-search-result
                frontend_type: html








    taxonomy-grid:
        options:
            entityHint: taxonomy
            entity_pagination: true
        acl_resource: oro_taxonomy_view
        source:
            type: orm
            query:
                select:
                    - t.id
                    - t.name
                    - COUNT(tt.id) as usage
                from:
                    - { table: OroTagBundle:Taxonomy, alias: t }
                join:
                    left:
                        tagging:
                            join: t.tags
                            alias: tt
                groupBy: t.id

        columns:
            name:
                label: oro.taxonomy.name.label
                type: field
                frontend_type: string
            usage:
                label: oro.tag.datagrid.usage_count
                type: field
                frontend_type: integer

        properties:
            id: ~
            update_link:
                type: url
                route: oro_taxonomy_update
                params:
                    - id
            search_link:
                type: url
                route: oro_taxonomy_update
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_taxonomy
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: t.name
                usage:
                    data_name: usage
            default:
                name: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

        filters:
            columns:
                name:
                    type: string
                    data_name: t.name
                usage:
                    type: number
                    data_name: usage
                    filter_by_having: true

        actions:
            search:
                type:          navigate
                label:         oro.tag.datagrid.search
                link:          search_link
                icon:          search
                acl_resource:  oro_taxonomy_view
                rowAction:     true
            update:
                type:          navigate
                label:         oro.grid.action.update
                link:          update_link
                icon:          edit
                acl_resource:  oro_taxonomy_update
            delete:
                type:          delete
                label:         oro.grid.action.delete
                link:          delete_link
                icon:          trash
                acl_resource:  oro_taxonomy_delete