parameters:
    importexport.filesystems_storage:  '../var/import_export'

knp_gaufrette:
    adapters:
        importexport:
            local:
                directory: '%kernel.root_dir%/%importexport.filesystems_storage%'
    filesystems:
        importexport:
            adapter:    importexport
            alias:      importexport_filesystem
