oro_entity_config:
    importexport:
        field:
            form:
                block_config:
                    import_export:
                        title:              oro.importexport.entity_config.block_title
                        priority:           30
            items:
                # custom field header, by default field label is used
                header:
                    options: []
                    form:
                        type:               oro_entity_extend_text
                        options:
                            label:          oro.importexport.entity_config.header.label
                            required:       false
                            block:          import_export
                            tooltip:        oro.importexport.entity_config.header.tooltip
                # field order in result file
                order:
                    options: []
                    form:
                        type:               integer
                        options:
                            label:          oro.importexport.entity_config.order.label
                            precision:      0
                            empty_data:     ''
                            required:       false
                            block:          import_export
                # is filed will be used to find existing entity
                identity:
                    options:
                        allowed_type: 
                            - string
                            - integer
                            - smallint
                            - bigint
                            - boolean
                            - decimal
                            - date
                            - text
                            - float
                            - money
                            - percent
                    form:
                        type:               oro_entity_extend_choice
                        options:
                            label:          oro.importexport.entity_config.identity.label
                            choices:
                                false:      'No'
                                true:       'Yes'
                            empty_value:    false
                            required:       false
                            block:          import_export
                # is field must be excluded from import/export
                excluded:
                    options: []
                    form:
                        type:               oro_entity_extend_choice
                        options:
                            label:          oro.importexport.entity_config.excluded.label
                            choices:
                                false:      'No'
                                true:       'Yes'
                            empty_value:    false
                            required:       false
                            block:          import_export
                # is relation must be represented by all it's fields
                full:
                    options:
                        allowed_type:       [ref-one, ref-many, manyToOne, oneToMany, manyToMany]
                    form:
                        type:               oro_entity_extend_choice
                        options:
                            label:          oro.importexport.entity_config.full.label
                            choices:
                                false:      'Identity only'
                                true:       'All'
                            empty_value:    false
                            required:       false
                            block:          import_export
                            tooltip:        'oro.importexport.entity_config.full.tooltip'

                # is relation field should be processed as scalar value when exporting data
                process_as_scalar:
                    options:
                        allowed_type:       [ref-one, ref-many, manyToOne, oneToMany, manyToMany, file, image]
                        default_value:      false
