services:
    oro_importexport.async.export:
        class: Oro\Bundle\ImportExportBundle\Async\ExportMessageProcessor
        arguments:
            - '@oro_importexport.handler.export'
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@oro_config.user'
            - '@oro_entity.doctrine_helper'
            - '@oro_security.security_facade'
            - '@security.token_storage'
            - '@logger'
            - '@oro_importexport.async.import_export_result_summarizer'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.pre_cli_import:
        class: Oro\Bundle\ImportExportBundle\Async\Import\PreCliImportMessageProcessor
        arguments:
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_message_queue.job.dependent_job_service'
            - '@oro_importexport.splitter.splitter_chain'
            - '@oro_importexport.file.file_manager'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.cli_import:
        class: Oro\Bundle\ImportExportBundle\Async\Import\CliImportMessageProcessor
        arguments:
            - '@oro_importexport.handler.import.cli'
            - '@oro_message_queue.job.runner'
            - '@oro_importexport.async.import_export_result_summarizer'
            - '@oro_message_queue.job.storage'
            - '@logger'
            - '@oro_importexport.file.file_manager'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.pre_http_import:
        class: Oro\Bundle\ImportExportBundle\Async\Import\PreHttpImportMessageProcessor
        arguments:
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_importexport.splitter.splitter_chain'
            - '@oro_message_queue.job.dependent_job_service'
            - '@oro_importexport.file.file_manager'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.http_import:
        class: Oro\Bundle\ImportExportBundle\Async\Import\HttpImportMessageProcessor
        arguments:
            - '@oro_importexport.handler.import.http'
            - '@oro_message_queue.job.runner'
            - '@oro_message_queue.client.message_producer'
            - '@doctrine'
            - '@security.token_storage'
            - '@oro_importexport.async.import_export_result_summarizer'
            - '@oro_message_queue.job.storage'
            - '@logger'
            - '@oro_importexport.file.file_manager'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.send_import_notification:
        class: Oro\Bundle\ImportExportBundle\Async\SendImportNotificationMessageProcessor
        arguments:
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_message_queue.job.storage'
            - '@oro_importexport.async.import_export_result_summarizer'
            - '@oro_config.user'
            - '@doctrine'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    oro_importexport.async.send_import_error_notification:
        class: Oro\Bundle\ImportExportBundle\Async\SendImportErrorNotificationMessageProcessor
        arguments:
            - '@oro_message_queue.client.message_producer'
            - '@logger'
            - '@oro_config.user'
            - '@doctrine'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }
