query_designer:
    grouping:
        exclude: [{type: text}, {type: array}, {type: json_array}, {type: simple_array}, {type: object}, {type: multiEnum}]

    filters:
        string:
            applicable: [{type: string}, {type: text}]
            type:       string
            query_type: [all]
        number:
            applicable: [{type: integer}, {type: smallint}, {type: bigint}, {type: decimal}, {type: float}, {type: money}]
            type:       number
            query_type: [all]
        date:
            applicable: [{type: date}]
            type:       date
            query_type: [all]
        datetime:
            applicable: [{type: datetime}]
            type:       datetime
            query_type: [all]
        boolean:
            applicable: [{type: boolean}]
            type:       boolean
            query_type: [all]
        percent:
            applicable: [{type: percent}]
            type:       percent
            query_type: [all]
        enum:
            applicable: [{type: enum}]
            type:       enum
            options:
                null_value: ':empty:'
                populate_default: true
                default_value: Any
                class: ''
            init_module: oroquerydesigner/js/enum-filter-initialized
            query_type: [all]
        multiEnum:
            applicable: [{type: multiEnum}]
            type:       multi_enum
            options:
                null_value: ':empty:'
                populate_default: true
                default_value: Any
                class: ''
            init_module: oroquerydesigner/js/enum-filter-initialized
            query_type: [all]
