placeholders:
    dots_menu:
        items:
            dots_menu_email:
                order: 100
    scripts_before:
        items:
            email_filter_templates:
                order: 5
    requirejs_config_extend:
        items:
            email_requirejs_config:
                order: 100

items:
    oro_send_email_button:
        template: OroEmailBundle:Email:activityButton.html.twig
        acl: oro_email_email_create
    oro_send_email_link:
        template: OroEmailBundle:Email:activityLink.html.twig
        acl: oro_email_email_create
    dots_menu_email:
        action: OroEmailBundle:Email:placeholderLast
        applicable: @oro_user.placeholder.filter->isUserApplicable()
    email_filter_templates:
        template: OroEmailBundle:Js:default_templates.js.twig
    email_requirejs_config:
        template: OroEmailBundle::requirejs.config.js.twig
        applicable: @oro_user.placeholder.filter->isUserApplicable()
