definitions:
    sync_email_body_after_email_synchronize:
        label:   Sync Email Body After Email Sync
        enabled: true
        order:   100
        entity:  Oro\Bundle\EmailBundle\Entity\Email
        actions_configuration:
            - @tree:
                conditions:
                    @blank: [$emailBody]
                actions:
                    - @format_string:
                        attribute: $.arguments
                        string: '--id=%id%'
                        arguments:
                            id: $id
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        flush: true
                        arguments:
                            - 'oro:email:body-sync'
                            - [$.arguments]
                            - true
                            - 'default'
                            - -50

    sync_email_flag_after_changed:
        label:   Sync Email Flag After Changed
        enabled: true
        order:   50
        entity:  Oro\Bundle\EmailBundle\Entity\EmailUser
        actions_configuration:
            - @tree:
                conditions:
                    @and:
                        - @not_empty: [$origin]
                        - @equal: [$origin.active, true]
                        - @equal: [$seen, false]
                actions:
                    - @format_string:
                        attribute: $.arguments
                        string: '--ids=%id%'
                        arguments:
                            id: $id
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        flush: true
                        arguments:
                            - 'oro:email:flag-sync'
                            - ['--seen=false', $.arguments]
            - @tree:
                conditions:
                    @and:
                        - @not_empty: [$origin]
                        - @equal: [$origin.active, true]
                        - @equal: [$seen, true]
                actions:
                    - @format_string:
                        attribute: $.arguments
                        string: '--ids=%id%'
                        arguments:
                            id: $id
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        flush: true
                        arguments:
                            - 'oro:email:flag-sync'
                            - ['--seen=true', $.arguments]

triggers:
    sync_email_body_after_email_synchronize:
        -
            event: create

    sync_email_flag_after_changed:
        -
            event: update
            field: seen
