aliases:
    oro/select2-attribute-autocomplete-component$: oroentityconfig/js/components/attribute-select-component
    oroentityconfig/js/attribute-group-collection-component$: oroentityconfig/js/components/attribute-group-collection-component
configs:
    oroentityconfig/js/sync/attribute-import-sync-notifier: {}
dynamic-imports:
    commons:
        - oro/select2-attribute-autocomplete-component
        - oroentityconfig/js/attribute-group-collection-component
        - oroentityconfig/js/sync/attribute-import-sync-notifier
