parameters:
    oro_note.entity.class:                              Oro\Bundle\NoteBundle\Entity\Note
    oro_note.placeholder.filter.class:                  Oro\Bundle\NoteBundle\Placeholder\PlaceholderFilter
    oro_note.migration.extension.note.class:            Oro\Bundle\NoteBundle\Migration\Extension\NoteExtension
    oro_note.entity_config_dumper.extension.class:      Oro\Bundle\NoteBundle\Tools\NoteEntityConfigDumperExtension
    oro_note.entity_generator.extension.class:          Oro\Bundle\NoteBundle\Tools\NoteEntityGeneratorExtension
    oro_note.manager.class:                             Oro\Bundle\NoteBundle\Entity\Manager\NoteManager
    oro_note.manager.api.class:                         Oro\Bundle\NoteBundle\Entity\Manager\ApiEntityManager
    oro_note.activity_list.provider.class:              Oro\Bundle\NoteBundle\Provider\NoteActivityListProvider

services:
    oro_note.manager:
        class: %oro_note.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.security_facade
            - @oro_security.acl_helper
            - @oro_entity.entity_name_resolver
            - @oro_attachment.manager

    oro_note.manager.api:
        class: %oro_note.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_note.entity.class%
            - @doctrine.orm.entity_manager

    oro_note.placeholder.filter:
        class: %oro_note.placeholder.filter.class%
        arguments:
            - @oro_entity_config.provider.note
            - @oro_entity_config.provider.entity
            - @oro_entity.doctrine_helper

    oro_note.entity_config_dumper.extension:
        class: %oro_note.entity_config_dumper.extension.class%
        parent: oro_entity_extend.entity_config_dumper.extension.association
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_note.entity_generator.extension:
        class: %oro_note.entity_generator.extension.class%
        tags:
            - { name: oro_entity_extend.entity_generator_extension }

    oro_note.migration.extension.note:
        class: %oro_note.migration.extension.note.class%
        tags:
            - { name: oro_migration.extension, extension_name: note }

    oro_note.widget_provider.actions:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - oro_add_note_button
            - oro_add_note_link
        tags:
            - { name: oro_ui.view_action_provider, group: activity, priority: -100 }
            - { name: oro_ui.update_action_provider, group: activity, priority: -100 }

    oro_note.activity_list.provider:
        class: %oro_note.activity_list.provider.class%
        arguments:
           - @oro_entity.doctrine_helper
           - @oro_security.owner.entity_owner_accessor.link
        tags:
           - {name: oro_activity_list.provider, priority: 40}
