config:
    paths:
        'orosegment/js/app/components/refresh-button': 'bundles/orosegment/js/app/components/refresh-button.js'
        'orosegment/js/app/components/segment': 'bundles/orosegment/js/app/components/segment.js'
