config:
    paths:
        'orosecurity/js/security-access-levels': 'bundles/orosecurity/js/security-access-levels.js'
        'orosecurity/js/init-organization-selector': 'bundles/orosecurity/js/init-organization-selector'
        'orosecurity/js/app/components/security-access-levels-component': 'bundles/orosecurity/js/app/components/security-access-levels-component.js'
        'orosecurity/js/app/models/share-with-datagrid-model': 'bundles/orosecurity/js/app/models/share-with-datagrid-model.js'
        'orosecurity/js/app/models/share-with-datagrid-collection': 'bundles/orosecurity/js/app/models/share-with-datagrid-collection.js'
        'orosecurity/js/app/views/share-with-datagrid-view': 'bundles/orosecurity/js/app/views/share-with-datagrid-view.js'
        'orosecurity/js/app/components/share-with-datagrid-component': 'bundles/orosecurity/js/app/components/share-with-datagrid-component.js'
        'orosecurity/js/app/components/shared-datagrid-component': 'bundles/orosecurity/js/app/components/shared-datagrid-component.js'
        'oro/select2-share-component': 'bundles/orosecurity/js/app/components/select2-share-component.js'
        'orosecurity/js/app/views/select2-share-view': 'bundles/orosecurity/js/app/views/select2-share-view.js'
        'orosecurity/js/app/helper/component-helper': 'bundles/orosecurity/js/app/helper/component-helper.js'
