services:
    oro_test.listener.step_duration_measure_subscriber:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Listener\StepDurationMeasureSubscriber'
        arguments:
            - '@definition.finder'

    oro_test.listener.feature_duration_subscriber:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Listener\FeatureDurationSubscriber'
        arguments:
            - '%kernel.log_dir%'

    oro_test.listener.interactive_execution_subscriber:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Listener\InteractiveExecutionSubscriber'

    oro_test.listener.js_logger_subscriber:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Listener\JsLogSubscriber'
        arguments:
            - '@mink'
            - '%kernel.log_dir%'
        tags:
            - { name: 'event_dispatcher.subscriber' }

    oro_test.listener.suite_aware_subscriber:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Listener\SuiteAwareSubscriber
        arguments:
            - ~
        tags:
            - { name: 'event_dispatcher.subscriber' }

    oro_element_factory:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Element\OroElementFactory'
        arguments:
            - '@mink'
            - '@mink.selectors_handler'
            - []
        tags:
            - { name: 'suite_aware' }

    oro_page_factory:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Element\OroPageFactory'
        arguments:
            - '@oro_element_factory'
            - []

    oro_behat_page_object_initializer:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Context\Initializer\OroPageObjectInitializer'
        arguments:
            - '@oro_element_factory'
            - '@oro_page_factory'
        tags:
            - { name: 'context.initializer' }

    oro_behat_session_alias_provider:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Context\SessionAliasProvider

    oro_behat_session_alias_initializer:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Context\Initializer\SessionAliasAwareInitializer'
        arguments:
            - '@oro_behat_session_alias_provider'
        tags:
            - { name: 'context.initializer' }

    oro_behat_fixture_loader_initializer:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Context\Initializer\FixtureLoaderInitializer
        arguments:
            - '@oro_test.context.fixture_loader'
        tags:
            - { name: 'context.initializer' }

    oro_behat_extension.message_queue_isolator_initializer:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Context\Initializer\MessageQueueIsolatorInitializer
        tags:
            - { name: 'context.initializer' }
            - { name: 'message_queue_isolator_aware' }

    oro_test.context.fixture_loader:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\FixtureLoader
        arguments:
            - '@symfony2_extension.kernel'
            - '@oro_test.entity_class_resolver'
            - '@oro_test.entity_supplement'
            - '@oro_test.alice_loader'
        tags:
            - { name: 'message_queue_isolator_aware' }

    oro_test.entity_class_resolver:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\EntityClassResolver
        arguments: ['@oro_entity.entity_alias_resolver']

    oro_test.entity_supplement:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\EntitySupplement
        arguments:
            - '@symfony2_extension.kernel'
            - '@oro_test.reference_repository'
            - '@oro_security.owner.metadata_provider.chain'

    oro_test.reference_repository:
        class: Nelmio\Alice\Instances\Collection
        factory: ['@oro_test.alice_loader', getReferenceRepository]

    oro_test.reference_repository_initializer:
        class: '%oro_test.reference_initializer_class%'
        arguments:
            - '@symfony2_extension.kernel'
            - '@oro_test.reference_repository'

    oro_behat_extension.fixtures.doctrine_entity_populator:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\DoctrineEntityPopulator
        arguments:
            - '@symfony2_extension.kernel'

    oro_behat_extension.fixtures.yml_parser:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\OroYamlParser
        arguments:
            - '@oro_test.alice_loader'
        calls:
            - [setKernel, ['@symfony2_extension.kernel']]

    oro_behat_extension.specification.specification_divider:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Specification\SpecificationCountDivider

    oro_behat_extension.specification.suite_configuration_divider:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Specification\SuiteConfigurationDivider
        arguments:
            - '@oro_behat_extension.specification.statistic.filesystem_statistic_repository'

    oro_behat_extension.specification.statistic.filesystem_statistic_repository:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Specification\Statistic\FilesystemStatisticRepository
        arguments:
            - '%kernel.root_dir%'

    oro_behat_extension.suite.suite_configuration_registry:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Suite\SuiteConfigurationRegistry
        arguments:
            - '@symfony2_extension.kernel'
            - '@specifications.finder'
            - '@oro_behat_extension.specification.specification_divider'
            - '@oro_behat_extension.specification.suite_configuration_divider'
        calls:
            - [setSuiteConfigurations, ['%suite.configurations%']]

    oro_test.alice_loader:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\OroAliceLoader
        calls:
            - [addPopulator, ['@oro_behat_extension.fixtures.doctrine_entity_populator']]
            - [addParser, ['@oro_behat_extension.fixtures.yml_parser']]

    oro_test.environment.handler.feature_environment_handler:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Environment\Handler\FeatureEnvironmentHandler
        arguments:
            - '@context.factory'
            - '@symfony2_extension.kernel'
        tags:
            - { name: 'environment.handler', priority: 100 }

    oro_test.context.oro_behat_class_resolver:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Context\OroBehatClassResolver
        arguments:
            - '@symfony2_extension.kernel'
        tags:
            - { name: 'context.class_resolver' }
